---

env:
  global:
    - CC_TEST_REPORTER_ID=d5c380e48e4f83365aa3878c05e1535569e07b907b986e1590b0570fe4339bb4

language: node_js
node_js:
  - node

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

scripts:
  - make lint
  - make test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT